momentohq/momento-cli

src/main.rs
This pr also contains an update to the rust sdk submodules. This update removes logging from within the grpc interceptors. No functionality changes
closes #10
=> feat: pretty print panic messages

src/main.rs
=> fix: conform arguments to posix conventions

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/commands/configure/configure.rs, src/main.rs, src/utils/file.rs, tests/configure_profiles_test.rs
=> fix: momento configure when user is first configuring momento

src/commands/configure/configure.rs
=> chore: default ttl to 600 seconds if empty

Cargo.lock, src/commands/configure/configure.rs
=> fix: update to latest rust sdk

src/commands/cache/cache.rs, src/commands/configure/configure.rs, src/main.rs, src/utils/file.rs, tests/configure_profiles_test.rs
Do we want to show them that we are creating a cache from them? Or should we hide the logging
=> feat: create default cache when configuring profile

src/commands/configure/configure_cli.rs, src/utils/file.rs, tests/momento_default_profile.rs
=> chore: Set file permission 600 for both credentials and config files

README.md
=> chore: add instructions on upgrading to readme

CONTRIBUTING.md, Cargo.lock, Cargo.toml, src/commands.rs, src/commands/cache/cache_cli.rs, src/commands/signingkey/mod.rs, src/commands/signingkey/signingkey_cli.rs, src/main.rs
Closes https://github.com/momentohq/momento-cli/issues/90
CLI command help:
```
% ./target/release/momento -h
momento 0.11.9
CLI for Momento APIs
USAGE:
momento [OPTIONS] <SUBCOMMAND>
OPTIONS:
-h, --help       Print help information
-V, --version    Print version information
--verbose
SUBCOMMANDS:
account      Account Managements
cache        Cache Operations
configure    Configure Momento Credentials
help         Print this message or the help of the given subcommand(s)
% ./target/release/momento account -h
momento-account
Account Managements
USAGE:
momento account [OPTIONS] <SUBCOMMAND>
OPTIONS:
-h, --help       Print help information
--verbose
SUBCOMMANDS:
create-signing-key    Creates a Momento Signing Key
help                  Print this message or the help of the given subcommand(s) …
```
=> feat: support create/revoke signing key

.github/workflows/cd.yml, .github/workflows/ci.yml, CONTRIBUTING.ja.md, CONTRIBUTING.md, Cargo.lock, Cargo.toml, src/commands/cache/cache_cli.rs, src/commands/signingkey/signingkey_cli.rs
=> chore: Use publicly available momento crate and remove client-sdk-rust submodule

.github/workflows/cd.yml
=> chore: Add a job to upload windows binary asset

.github/workflows/cd.yml, src/commands/configure/configure_cli.rs, src/utils/file.rs
Addresses some of the issues mentioned in https://github.com/momentohq/momento-cli/issues/122
Comment out uploading Windows binary 32 to make sure 64 binary gets uploaded successfully first.
=> fix: Upload Windows binary file 64

Cargo.lock, Cargo.toml, src/commands/login.rs, src/main.rs
`momento login qr`
Prints a unicode QR image for you to log in via your phone.
`momento login` defaults to `momento login browser`.
=> feat: qr code login option

Cargo.lock, Cargo.toml, src/commands/cache/cache_cli.rs, src/commands/configure/configure_cli.rs, src/commands/signingkey/signingkey_cli.rs, src/main.rs, src/utils/client.rs
Adding a `--endpoint` option that would allow to specify what momento endpoint to use for cli operations to connect to.
=> feat: Add endpoint flag option

.github/workflows/ci.yml, Cargo.toml, run_test_sequentially.sh, src/commands/mod.rs, src/main.rs, src/utils/file.rs, src/utils/user.rs
The login option is still actively under construction. In order to separate this from other stable features, we have classified the login functionality as a conditionally compiled feature. By default login will not be included, but may be adding `--features login` to `cargo build` or `cargo run`.
Closes #167
=> feat: bundle login as separate feature

.github/workflows/cd.yml
hopefully fixes https://github.com/momentohq/oncall-tracker/issues/136 🤞
=> chore: try and solve release race condition

README.md, src/main.rs
`ap-northeast1` -> `asia-northeast1`
=> fix: Correct the GCP Region in help

.github/workflows/on-push-to-release.yml
Added a job to release rpm (x86_64) package.
I would like to merge this to see this job does what I expect before adding other jobs to release deb (x86_64) package and both packages in arm64.
Related ticket: https://github.com/momentohq/momento-cli/issues/176
=> chore: release rpm (x86_64) package 

.github/workflows/on-pull-request.yml, Cargo.lock, Cargo.toml, src/commands/cache/cache_cli.rs, src/commands/configure/configure_cli.rs, src/commands/login.rs, src/main.rs, src/utils/client.rs, src/utils/file.rs, src/utils/user.rs, tests/configure_profiles_test.rs, tests/momento_additional_profile.rs, tests/momento_default_profile.rs
* update clap command line parser, use the preferred macros
* update other libraries
* consolidate endpoint flags, make them not so position dependent
* fix all clippy violations
* add some help docs
* fix all clippy violations
* bring `momento` pr's to the normal Momento clippy low-bar threshold (still allowing expect by default)
We did all that work a while back to add CliError, so I fixed all of the straggler call sites still using unwrap().
An example of probably the most complex command we currently have:
```
momento cache set --help`
Store an item in a cache
Usage: momento cache set [OPTIONS] <KEY|--key <KEY>> <VALUE|--value <VALUE>>
Arguments:
[KEY]    Cache key under which to store the value
[VALUE]  Cache value to store under the key. This will be stored as UTF-8 bytes.
Options: …
```
=> feat: improve & refresh cli

.github/workflows/execute-release.yml, .github/workflows/on-push-to-main.yml
mispasted yaml on a prior change.
=> fix: windows protoc installation

src/commands/configure/configure_cli.rs, src/utils/ini_config.rs
This commit contains no functional changes, just a refactor. Prior to this commit there was some ini-specific logic for finding profiles defined in the configure_cli mod.  This commit moves it to the ini_config mod so we can try to keep all of the ini-specific logic there.
In addition, the `update_profile_values` fn in ini_config required you to pass in information about all of the profile line numbers as arguments; this made it very fragile to write tests, because you either needed to call a separate function to determine those line numbers or maintain the test line numbers by hand.  This commit encapsulates the line number logic inside of the function, so that callers don't have to worry about it and tests are less fragile.
=> chore: simplify signature for ini update_profile_values

CONTRIBUTING.md, momento/src/commands/configure/configure_cli.rs, momento/src/config.rs, momento/src/main.rs, momento/src/utils/file.rs, momento/src/utils/ini_config.rs, momento/src/utils/mod.rs, momento/src/utils/user.rs, momento/tests/common/mod.rs
This reverts commit 0e7e292b79423889944f0a8cf82599495b048f19, reversing
changes made to 5f9e40df0455bb4a94dd7a4160980dacb4bbc2e2.
=> Revert "Merge pull request #277 from momentohq/fix/file-handling-update"

README.md, README.pt.md, momento-cli-opts/src/lib.rs
https://github.com/momentohq/core-infrastructure/issues/512
=> chore: Deprecating us-east1 as us-east4 is now setup.

.gitignore, momento-cli-opts/src/lib.rs, momento/src/commands/cloud_linter/api_gateway.rs, momento/src/commands/cloud_linter/dynamodb.rs, momento/src/commands/cloud_linter/elasticache.rs, momento/src/commands/cloud_linter/linter_cli.rs, momento/src/commands/cloud_linter/metrics.rs, momento/src/commands/cloud_linter/resource.rs, momento/src/commands/cloud_linter/s3.rs, momento/src/commands/cloud_linter/serverless_elasticache.rs, momento/src/main.rs
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/856
=> feat: speed up resource collection, add resource specific cli flags

momento/src/commands/cloud_linter/elasticache.rs, momento/src/commands/cloud_linter/linter_cli.rs, momento/src/commands/cloud_linter/metrics.rs, momento/src/commands/cloud_linter/s3.rs, momento/src/commands/cloud_linter/serverless_elasticache.rs
=> feat: speed up resource collection for elasticache
