- Cargo.lock
- Cargo.toml
Build is failing on linux due to a transient dependency on openssl. Removing this unecessary transient depedency
https://github.com/momentohq/homebrew-tap/runs/4221608465?check_suite_focus=true
https://github.com/seanmonstar/reqwest/issues/1288
https://github.com/Homebrew/homebrew-test-bot/issues/661
> fix: removing dep on openssl to fix linux build

- Cargo.lock
- Cargo.toml
- src/commands/account.rs
- src/commands/cache/cache.rs
- src/commands/configure/configure.rs
- src/error/mod.rs
- src/main.rs
- src/utils/file.rs
- src/utils/user.rs
closes #42 
closes #41 
Right now, I just implemented 1 error type called `CliError`, but I figured that we could pretty easily add more custom error types down the line, and each can be formatted appropriately
> feat: pretty print cli error messages

- CONTRIBUTING.md
- src/commands/cache/cache.rs
Follow-up to https://github.com/momentohq/client-sdk-rust/pull/13
- update CONTRIBUTING.md with command that ensures we pull the latest commits from submodules
- fix: update CLI to consume new Rust SDK changes
Only updates our CLI to consume new API changes for managing `SimpleCacheClient` objects.
Testing:
* `cargo build && cargo test`
* `cargo fmt`
* Run CLI against dev cell:
```
Tylers-MacBook-Pro :: ~/repo/momento-cli ‹update-sdk-consumption› » ./target/debug/momento cache list
[2022-02-03T17:45:52Z INFO  momento::commands::cache::cache] list cache called
example-cache
cache
Tylers-MacBook-Pro :: ~/repo/momento-cli ‹update-sdk-consumption› » ./target/debug/momento cache create --name fooBarBaz
[2022-02-03T17:46:01Z INFO  momento::commands::cache::cache] create cache called …
```
> Update CLI to consume new Rust SDK changes

- CONTRIBUTING.ja.md
- CONTRIBUTING.md
- README.ja.md
- README.md
Added JP translation for both `README` and `CONTRIBUTING`
@danielamiao - It seems like the example has table of contents but since this README is short I'm not sure if it's needed. 
I skipped it for now.
> chore: Add JP translation for README and CONTRIBUTING

- Cargo.lock
- Cargo.toml
- src/commands/configure/configure.rs
- src/main.rs
- src/utils/file.rs
- src/utils/user.rs
Conducted local test scenarios:
- Run `momento cache list --profile <profile>` to check if we can specify a profile. When `--profile` is not specified, `default` profile will be used.
<br>
- Run `momento configure` without credentials or config files -> create new credentials and config files with `[default]` section in INI format.
<br>
- Run `momento configure` only with existing credentials file -> create a new config file with [default]` section in INI format and throw an error saying that the credentials file already exists.
<br>
- Run `momento configure` only with existing config file -> create a new credentials file with [default]` section in INI format and throw an error saying that the config file already exists.
<br>
- Run `momento configure` with both existing credentials and …
> feat: Add support for multiple profiles and only allow new credentials/config files creations

- src/commands/cache/cache_cli.rs
- src/commands/configure/configure_cli.rs
- src/config.rs
- src/main.rs
- src/utils/user.rs
* Updates CLI with latest Momento Rust SDK
* Updates CLI to use `uint64` when handling `ttl_seconds`
> chore: update cli with latest sdk changes, use uint64 for ttl

- Cargo.lock
- Cargo.toml
- src/commands/cache/cache_cli.rs
Using `new_momento_cli` allows us to send momento-cli agent value to differentiate it from our Rust SDK agent value.
Closes #102
> chore: Update to use `new_momento_cli` to initialize a Momento client

- README.ja.md
- README.md
- src/commands/configure/configure_cli.rs
- src/main.rs
Added `--quick` flag to use the default cache name and TTL without users entering anything.
Users are still required to enter their auth token.
First time creating `default-cache`
```
./target/debug/momento configure --quick
Token [****]: gregger
[2022-04-13T18:28:40Z INFO  momento::commands::configure::configure_cli] default-cache successfully created with default TTL of 600s
```
`default-cache` already exists
```
./target/debug/momento configure --quick
Token [****]: gdfgfdg
[2022-04-13T18:29:14Z INFO  momento::commands::configure::configure_cli] default-cache already exists
```
Closes #109
> chore: Add `--quick` flag to use default cache name and TTL on `momento configure`

- src/commands/cache/cache_cli.rs
- src/main.rs
- Exit with code 1 on cache miss
```
./target/debug/momento cache get --key erika
echo $?                                     
1
```
- Add `--quiet` flag on the set command so that `[2022-04-13T20:55:58Z INFO  momento::commands::cache::cache_cli] cache miss` won't be displayed
Closes #108
> chore: Improve cache miss handling

- .github/workflows/cd.yml
@eaddingtonwhite figured out that we can build binary for Linux can be used on Ubuntu, CentOS, and Amazon Linux AMIs by building binary in a Docker container with [quay.io/pypa/manylinux2014_x86_64](http://quay.io/pypa/manylinux2014_x86_64) image.
Utilizing the `container`(https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer)  workflow syntax, build momento cli binary, tar.gz, and upload it as a GH asset.
Closes #97
> chore: Add `publish-linux-assets` job to cd workflow

- .github/workflows/cd.yml
- README.ja.md
- README.md
- Updated the CD workflow to only compress the momento binary file
- Updated both English and Japanese README to include installation instructions for Linux (referenced the Stripe doc: https://stripe.com/docs/stripe-cli#install)
> chore: Update `README` and CD workflow

- .github/workflows/cd.yml
- README.ja.md
- README.md
We successfully uploaded Windows 64-bit binary to GH Asset.
Spent some time to do the same for 32-bit binary; however it's not a priority to build 32-bit right now so we decided to postpone until customers ask for it.
Therefore, commenting out the building i686 step. 
Closes #122
> chore: comment out windows_i686 build step

- Cargo.lock
- Cargo.toml
- src/commands/signingkey/signingkey_cli.rs
- src/main.rs
Adds CLI support for new `ListSigningKeys` API. This also consumes the latest changes from the Rust SDK to display a Momento signing key's `expires_at` field as a UTC timestamp.
* Create a signing key to demonstrate new `expires_at` return value
```sh
Tylers-MacBook-Pro :: ~/repo/momento-cli ‹signing-keys*› » ./target/debug/momento account create-signing-key --ttl 30 --profile personal-prod
{
"key_id": "5fhrnelif",
"key": "<redacted>",
"expires_at": "2022-04-22T23:04:17Z",
"endpoint": "cache.cell-external-beta-1.prod.a.momentohq.com"
}
```
* List my account's signing keys
```sh
Tylers-MacBook-Pro :: ~/repo/momento-cli ‹signing-keys*› » ./target/debug/momento account list-signing-keys --profile personal-prod
[
{
"key_id": "qhyssqxro",
"expires_at": "2022-04-22T23:00:59Z",
"endpoint": …
```
> feat: add support for ListSigningKeys API

- README.md
- src/commands/account.rs
- src/main.rs
Signup
```
momento account signup gcp --email myemail@mydomain.com --region us-east1
```
This also updates the signup pattern for AWS, now it will be:
```
momento account signup aws --email myemail@mydomain.com --region us-west-2
```
Once, we agree upon the README in English. I will need help from @poppoerika to update the Japanese language README.
> feat: Allow signups for Momento on GCP

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/commands/cache/cache_cli.rs
- src/commands/signingkey/signingkey_cli.rs
- src/utils/client.rs
- src/utils/mod.rs
This change establishes a common pattern for interacting with the
service. Rather than copy/pasting matches, MomentoError -> CliError
mapping and json dump code around, this names those functionalities
as functions:
* interact_with_momento: Completes a momento future and maps the
result to a Result< HappyCaseType, CliError >
* print_whatever_this_is_as_json: prints whatever you feed it as json
This change was precipitated by the change in the SDK to simplify
and coalesce client creation behind the SimpleCacheClientBuilder and
triggered by the SDK upgrade.
There are small changes to debug and error messages, but this change
should cause no functional changes.
tired of copypasta.
```
pub async fn delete_cache(cache_name: String, auth_token: String) -> Result<(), CliError> {
debug!("deleting …
```
> chore: upgrade momento sdk - consistency, less copypasta

- Cargo.lock
- Cargo.toml
- src/commands/login.rs
- src/commands/mod.rs
- src/main.rs
Adds `momento login` command for doing SSO. The integration has
a live connection back up to the Momento endpoint that it running
the login workflow.
A standard oauth dance happens, with a browser opening up to an
SSO page. Some infos are printed from the server while you're
logging in, then the login credentials are printed to stdout.
We will be moving this session token to a momento dotfile, but
this change gets the SSO integration started. Not many endpoints
are supported, but over time we'll add more.
> feat: add `login` command

- Cargo.lock
- Cargo.toml
- src/commands/login.rs
- src/config.rs
- src/main.rs
- src/utils/user.rs
Also uses sessions if they're valid for at least 10 more seconds.
This breaks interactions with the service currently if you have
an active login session, because session tokens do not have the
momento endpoints baked into them.
> feat: store session tokens in .momento_session

- README.md
The command `brew update momento-cli` fails with an error: 
```
Error: This command updates brew itself, and does not take formula names.
Use `brew upgrade momento-cli` instead.
```
I think we need just `brew update`.  I don't like this because it potentially touches a bunch of stuff that a user isn't trying to upgrade, but it won't work if you pass it a formula name, and I don't know how to update a single formula, and I don't think the `brew upgrade momento-cli` command actually works without the `update` before it?
> fix: broken brew update command in README

- src/main.rs
Closes #168 
Before
```
momento account signup gcp --email eem@momentohq.com
error: The following required arguments were not provided:
--region <REGION>
```
After
```
target/debug/momento account signup gcp --email eem@momentohq.com
error: The following required arguments were not provided:
--region <us-east1 or ap-northeast1>
```
Before
```
momento account signup aws --email eem@momentohq.com --region fgfs
[2022-10-13T04:37:39Z INFO  momento::commands::account] Signing up for Momento...
ERROR: Failed to create Momento token: Region 'fgfs' is not a valid region for AWS. The available regions are: us-west-2, us-east-1, ap-northeast-1
```
After
```
target/debug/momento account signup gcp
--email eem@momentohq.com --region dcasdfafaf
error: "dcasdfafaf" isn't a valid value for '--region …
```
> fix: display available regions for aws/gcp for better error handling

- src/commands/account.rs
- src/commands/cache/cache_cli.rs
- src/commands/configure/configure_cli.rs
- src/commands/login.rs
- src/main.rs
- src/utils/client.rs
- src/utils/console.rs
- src/utils/mod.rs
This turns off logging when not verbose. Verbose logging is set to `debug` level. As discussed in #172 we find the log data _too_ verbose compared to the other status messages or normal cache response data.
We replace other print statements with one of two new macros.
We funnel all status or error print statements to `stderr` with `console_info!`. Similarly we define a macro `console_data!` for cache response data, which we print to `stdout`.
Closes #172
> chore: only use logging when verbose

- .github/workflows/on-push-to-release.yml
When `main` tried to be merged into `release`, a release version was missing from `Update Cargo Version` step in `on-push-to-release` workflow, so removed `dry-run` option from semrel.
Related: https://github.com/momentohq/momento-cli/issues/177
> fix: remove dry run from semrel step

- .github/workflows/on-push-to-release.yml
Needs to pass `--no-ci` flag to run semrel on non-default branch (in our case `release`)
> fix: pass custom arg to run semrel on non default branch

- .github/workflows/on-push-to-release.yml
There is one more step to add a semrel custom arg to run the release step on `release` branch.
> fix: add custom arg to semrel release step to run this step in non-main branch

- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
- .github/workflows/on-push-to-release.yml
- tests/configure_profiles_test.rs
- tests/momento_additional_profile.rs
- tests/momento_default_profile.rs
Ran the latest momento-cli on an Amazon Linux EC2 instance, and the version was not the oldest `0.11.9` as described in [this ticket](https://github.com/momentohq/momento-cli/issues/181), but it was off by one minor version (supposed to be `0.22.6` but it was `0.22.5`).
I believe this is happening because the cli is built and released before the cargo version is updated and pushed to `release` branch so when the cli is build and released on the publishing assets jobs, it's still referencing the previous version listed in `cargo.toml`.
I added `update-cargo` as one of the needed jobs for both publishing jobs, so hoping that would fix the above issue.
Once this is merged and run the manual release and verify its version on the Linux machine, I will close the ticket: …
> fix: add one more param to `needs` in publishing assets jobs on release

- .github/workflows/on-push-to-release.yml
Since we don't use `PRIVATE_REPO_RELEASE_ACCESS` as a GH secret anymore, updated the token we're using the release workflow to `MOMENTO_MACHINE_USER_GITHUB_TOKEN`.
> fix: update token in release workflow

- .github/workflows/on-push-to-release.yml
Even though Cargo version is updated in the `update-cargo` job, the change will only apply to the `release` branch after this workflow is done running.
So we might need to add a step to update Cargo version in the `publish-linux-assets`  job as well to display the correct version.
> fix: add a step to update cargo version in publish-linux-assets job

- src/commands/account.rs
- tests/momento_additional_profile.rs
- tests/momento_default_profile.rs
When I forced to use TLS version 1.3 (set minimum TLS version to 1.3) on both Mac and Windows, I received the below error:
**Mac OS**
```
./target/debug/momento account --verbose signup aws --email eem@momentohq.com --region us-west-2
Signing up for Momento...
[2022-12-06T18:05:40Z DEBUG reqwest::connect] starting new connection: https://signup.registry.prod.a.momentohq.com/
[2022-12-06T18:05:40Z DEBUG hyper::client::connect::dns] resolving host="signup.registry.prod.a.momentohq.com"
[2022-12-06T18:05:40Z DEBUG hyper::client::connect::http] connecting to 44.237.124.50:443
[2022-12-06T18:05:40Z DEBUG hyper::client::connect::http] connected to 44.237.124.50:443
[2022-12-06T18:05:40Z DEBUG rustls::client::hs] No cached session for DnsName(DnsName(DnsName("signup.registry.prod.a.momentohq.com" …
```
> chore: set max TLS version to 1.2

- .github/workflows/on-push-to-release.yml
Fixed the incorrect version number reference that was used to update cargo version in the `publish-linux-asset` job.
Also, added a step to update cargo version in the `publish-windows-asset` job.
> fix: reference proper version number

- .github/workflows/on-push-to-release.yml
I found out that the container used for the `publish-linux-asset` job, `quay.io/pypa/manylinux2014_x86_64`, does not work well with `actions/setup-python@v2`.
Therefore, I removed that action and installed python3 and pip3 with yum.
Tested locally with the exact same image, `quay.io/pypa/manylinux2014_x86_64`, and I was able to run `set_cargo_version.sh` successfully.
I also removed the container from the `publish-rpm-package` job to remove any complexity since we don't need to use a container to run this job.
This PR should make the `on-push-to-release` workflow run successfully and update the momento-cli version; therefore,
1. linux asset will be successfully released
2. correct momento-cli version will be displayed on linux
3. rpm package (x86_64) will be released 
🤞 
@cprice404 …
> fix:`on-push-to-release` workflow

- .github/workflows/on-push-to-release.yml
The `publish-rpm-package` job was failed because the wrong version reference was passed and an empty version was passed to create a rpm package.
https://github.com/momentohq/momento-cli/actions/runs/3659355567/jobs/6185405904#step:8:22
Use a correct reference to the release version.
> fix: use correct version reference

- .github/workflows/on-push-to-release.yml
This commit attempts to fix two current failures in the release
process:
1. The rpm release is failing because we try to do a `yum install jq`
on ubuntu, which hopefully shouldn't be necessary, i am expecting
the ubuntu image already has jq.
2. The windows install fails due to missing github auth token when
making an API call t get the release url.
> fix: no yum on ubuntu, try to pass GH auth header for Windows

- .github/workflows/on-push-to-release.yml
- README.md
- nfpm.template.yaml
This commit changes several things as we work toward finishing
out linux support (rpms, debs, and ARM builds):
* Attempt to do the Cargo.toml file update only once, at the
beginning.
* Switches off of jiro4989/build-rpm-action in favor of using nfpm;
this is because I tested the rpms generated by jiro4989 and they
did not work on most of the RHEL platforms (such as AL2); I have
tested rpms and debs built by nfpm on ubuntu, debian, centos,
rhel, and AL2 and they work on all of them.
* Adds ARM into the arch matrix.
This is going to fail, so I left a lot of the previously working
code in place and commented out in case we need to refer back to
it as we are working out the kinks.  I will clean up all of the
commented code once things are working.
> fix: working on rpm, deb, and arm builds

- .github/workflows/on-push-to-release.yml
the deb filename has an underscore instead of a dot.
> chore: fix syntax for deb filename in linux release

- .github/workflows/execute-release.yml
- tests/configure_profiles_test.rs
- tests/momento_additional_profile.rs
- tests/momento_default_profile.rs
This commit changes the code that produces the archive files
so that the momento binary will be at the root.  It seems as
though homebrew formulae won't work properly for linux if the
binary is at a nested path.
> chore: put momento binary at root of archive files

- .github/workflows/execute-release.yml
We use a code signing certificate to sign the windows binary and windows installer. We also refactor the publish-windows-assets job steps to be more self contained.
> chore: sign windows installer

- windows/installer/MomentoCLI.wixproj
- windows/installer/Product.wxs
Because the company name in the copyright is lowercase ("momento"), we ensure the installer metadata and winget packages list the company name lowercased too. This PR updates the installer.
> chore: normalize case to be in line with winget release

- .github/workflows/execute-release.yml
- windows/installer/Product.wxs
WinGet has conventions regarding the manufacturer name and application name. The WinGet metadata must also match this. Here we adjust the manufacturer name and application name to be title cased. We also remove the build number from the installer version.
> chore: integrate winget contributor feedback

- .github/workflows/execute-release.yml
Updates the momento cli entry in the WinGet package manager on release. Incrementally updates the manifests with the newest version number and installer location.
> chore: update winget on release

- .github/workflows/execute-release.yml
We believe that the `wingetcreate update` command requires
fine-grained permissions to create a pull request from a fork. Because
of this we try using the momento machine PAT.
> chore: use momento machine pat for winget update

- src/commands/configure/configure_cli.rs
Prior to this commit if the user ran configure more than once, on the second and subsequent attempts they would get a confusing message printed about the default cache already existing.  This commit removes that message as it doesn't provide any real value to the user.
> fix: don't log confusing message if the user runs configure a second time

- README.md
We add winget as the primary installation path for Windows users. Previously the only
installation path was by downloading the installer/zip from the GitHub
release page. We demote this to an alternative path.
> chore: update windows install instructions for winget

- .github/workflows/execute-release.yml
- .github/workflows/manual-release.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
- Cargo.lock
- Cargo.toml
- scripts/install_protoc.sh
- scripts/install_protoc_linux.sh
- scripts/install_protoc_osx.sh
- scripts/install_protoc_windows.sh
- src/commands/cache/cache_cli.rs
- src/commands/login.rs
- src/commands/mod.rs
- src/commands/topic/mod.rs
- src/main.rs
- src/utils/client.rs
Add a simple ability to publish and subscribe to momento topics.
Once this feature is stabilized we can remove the preview header.
example:
```bash
momento topic subscribe a_topic
```
```bash
momento topic publish a_topic 'hello there'
```
```
Interact with topics
!!                            !!
!!       Preview feature      !!
!!  Your feedback is welcome  !!
!!                            !!
These commands requires a cache, which serves as a namespace
for your topics. If you haven't already, call `cache create`
to make one!
To create a topic, subscribe to it.
To delete a topic, stop subscribing to it.
Usage: momento topic [OPTIONS] <COMMAND>
Commands:
publish
Publish a value to all subscribers of a topic
subscribe
Subscribe to messages coming in on a topic
help
Print this message or the …
```
> feat: Topics preview

- src/commands/account.rs
- src/commands/configure/configure_cli.rs
- src/commands/login.rs
- src/utils/console.rs
- src/utils/file.rs
- src/utils/ini_config.rs
- src/utils/user.rs
This commit just adds some early unit tests for the ini_config
module.  A minor refactor was required for some separation of
concerns so that the tests could be written without writing
files to disk.
In subsequent commits the functions in the ini_config will be
refactored further to make them more testable, but this commit
gets the tests in place so that we can hopefully ensure that
we don't break any functionality in the subsequent refactor.
The end goal here is to fix some issues that users reported
where empty tokens don't get updated properly, or leading/trailing
whitespace entered in the CLI input cause corruption to the
files; this will be addressed in later commits once the code
can be tested more easily.
> chore: add some initial basic tests for config/creds ini interactions

- src/commands/configure/configure_cli.rs
- src/utils/ini_config.rs
This commit changes the signatures of several functions in the ini_config module to accept slices of &str or String, rather than just Vec<String>, so that we don't need to do so much cloning before calling these functions.  Also removes calls to clone in several call sites.
> chore: refactor ini signatures to accept &str to reduce cloning

- src/commands/configure/configure_cli.rs
- src/utils/ini_config.rs
A user reported that if the credentials file has an empty token (e.g. if they pressed enter without pasting a token in when running the configure command), subsequent calls to the configure command did not update the file properly.
This commit adds test coverage for this case and fixes the bug that was preventing the new value from being written.
> fix: add tests to cover case with empty token in config file, fix bug

- Cargo.lock
- Cargo.toml
- src/commands/configure/configure_cli.rs
- src/config.rs
- src/utils/ini_config.rs
This PR contains a series of commits that make simplifications to the code for updating the config/credentials files.  Should be easier to maintain as a result, as well as significantly reducing the number of copy operations that are being made when updating the files.
> chore: simplify logic for updating config/credentials files

- Cargo.toml
this docker image uses x86_64 to cross compile to aarch64, even on
aarch64 hosts, so x64_64 is the right protoc version.
Scripts aren't conveniently on the build path or I would have invoked
the script. However, we need to remove this protoc dependency from our
client_protos package anyway so I'm not going to over-engineer this
> fix: add protoc for aarch64 cross build

- Cargo.toml
this docker image uses x86_64 to cross compile to x86_64, even on
aarch64 hosts, so x64_64 is the right protoc version.
Scripts aren't conveniently on the build path or I would have invoked
the script. However, we need to remove this protoc dependency from our
client_protos package anyway so I'm not going to over-engineer this
> fix: add protoc for x86_64 cross build

- .gitignore
- Cargo.lock
- Cargo.toml
- src/commands/login.rs
- src/main.rs
- src/utils/client.rs
- tests/momento_additional_profile_test.rs
consume the latest sdk with the new error types. This also lets
`topic subscribe` do a little bit better with output when the
connection is interrupted without an error - whether due to
inactivity or a service deployment and h2 goaway.
> chore: update sdk

- Cargo.lock
- momento/Cargo.toml
Bumping the SDK version for heartbeart support. Interrupted
will now happen for this class of timeout instead of a stream
read error.
Here's a fresh subscription receiving a heartbeat on subscribe:
```
$ momento -p alpha topic subscribe asd --cache roflmao --verbose
[2023-02-16T00:42:56Z DEBUG momento::utils::user] Token already expired at: 2022-06-02 23:54:38 UTC
[2023-02-16T00:42:56Z DEBUG momento::utils::user] No session found in .momento_session profile...
[2023-02-16T00:42:56Z DEBUG rustls::anchors] add_parsable_certificates processed 166 valid and 0 invalid certs
[2023-02-16T00:42:56Z DEBUG hyper::client::connect::dns] resolving host="cache.cell-alpha-dev.preprod.a.momentohq.com"
[2023-02-16T00:42:56Z DEBUG hyper::client::connect::http] connecting to 54.186.170.81:443 …
```
> chore: add heartbeat support

- Cargo.lock
- momento-cli-opts/src/lib.rs
- momento/Cargo.toml
- momento/build.rs
In a subsequent commit we will need to package these in the appropriate places in the releases in order for them to work.
> chore: generate zsh/bash completion scripts

- momento-cli-opts/src/lib.rs
The zsh/bash completion is showing the hidden preview features
even though they don't show up in help.  Prior to this commit
the wording for the help message for the topics subcommand
looked really bad in zsh tab completion; this commit should
make it look more reasonable.
> chore: re-word help messages for preview features

- momento-cli-opts/src/lib.rs
This commit moves the signing key command to "preview" status,
so that it doesn't show up in the default help.  It will still
show up in tab completion at the root of the command, but
is now prefixed with our "**PREVIEW**" label, and includes some
information in the subcommand help text about its preview status.
> feat: hide signing key command from help, improve preview text

- momento-cli-opts/src/lib.rs
- momento/src/main.rs
- momento/tests/momento_additional_profile_test.rs
creates a new subcommand `preview` to put features that are still being worked on. It is not hidden, since we are clearly marking every command under `preview` as not fully productionized. 
- `**Preview**` text removed from topics command description
- moved `singing-keys` and `login` subcommands under `preview` functionality
> feat: add new preview subcommand for beta features

- Cargo.lock
- momento-cli-opts/src/lib.rs
- momento/Cargo.toml
- momento/src/commands/mod.rs
- momento/src/commands/tokens/mod.rs
- momento/src/main.rs
`momento preview generate-token --never-expire --profile alpha`
```
{
"api_token": "<token>",
"refresh_token": "",
"valid_until": {
"secs_since_epoch": 1678213596,
"nanos_since_epoch": 0
}
}
```
Since this command is in preview, only engineers who have internal tokens will be able to use it.
closes https://github.com/momentohq/momento-cli/issues/272
> feat: add preview command to generate api tokens

- momento-cli-opts/src/lib.rs
- momento/src/commands/cache/cache_cli.rs
- momento/src/main.rs
- momento/tests/momento_additional_profile_test.rs
Added support to delete an item for a cache. Since we already had ```delete``` as a cache subcommand to delete the cache, I went with ```delete-item``` for this one. Let me know if you have better suggestions.
How was this change tested?
- Manually ran ```./target/debug/momento cache delete-item``` for a key I had inserted and verified it got deleted from the cache. A non-existent key doesn't throw an error.
- Added a test case for command verification similar to other commands.
> feat: add support for deleting an item from cli

- momento-cli-opts/src/lib.rs
- momento/src/main.rs
Add a cloud-linter command to the preview section of the cli. It doesn't do anything yet.
> feat: Add initial cloud linter command to preview

- Cargo.lock
- momento/Cargo.toml
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/mod.rs
- momento/src/commands/mod.rs
Add a function that executes another function with a rate limit. Will be used in the cloud linter.
Update the clap dependency to try and fix an error about using a nightly feature.
> feat: Add rate limiting function

- Cargo.lock
- momento-cli-opts/src/lib.rs
- momento/Cargo.toml
- momento/src/commands/cloud_linter/dynamodb.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/mod.rs
- momento/src/commands/cloud_linter/utils.rs
- momento/src/commands/mod.rs
- momento/src/main.rs
Update the preview cloud linter command to query for ElastiCache and DynamoDB metadata.
Serialize the metadata and print out the JSON in the command to show it is working. File creation will come after the metrics are added.
Move the rate limiting code to a new utils file.
> feat: Add ElastiCache and DynamoDB metadata to the cloud linter

- Cargo.lock
- momento/Cargo.toml
- momento/src/commands/cloud_linter/dynamodb.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/metrics.rs
- momento/src/commands/cloud_linter/mod.rs
- momento/src/commands/cloud_linter/resource.rs
Change the get metadata functions for dynamo and elasticache to return a resource that will later be serialized into json.
Add code for fetching metrics based on the dynamo and elasticache resources.
Change the linter cli to print out the full json including the metrics.
> feat: fetch metrics for the dynamo and elasticache resources

- Cargo.lock
- momento/Cargo.toml
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/utils.rs
Add a step to check if the output file will be writable before making any network calls.
Gzip compress the final json and write it to linter_results.json.gz in the directory the linter command is executed from.
Check the AWS credentials before starting to provide a better error message than would occur if we made an AWS call with invalid credentials.
> feat: write linter output to a gzipped JSON file

- momento/src/commands/cloud_linter/dynamodb.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/metrics.rs
- momento/src/commands/cloud_linter/resource.rs
The describe_time_to_live api call is heavily throttled, we don't want to have to call it for every dynamodb table. This pr separates out the describe ttl call into a separate function, and only calls it on tables who have at least an average of 100tps over the course of a month. We can tune this heuristic later on
Before
After
> fix: use heuristics to determine when to query ddb table ttl

- .github/workflows/execute-release.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
There are a ton of deprecation warnings when running github actions within this repo
This pr takes a stab at trying to eliminate some of them
> fix: update actions to remove deprecated nodejs versions

- .github/workflows/execute-release.yml
Now I'm thinking that all the ones that happen on Windows need
to be `$ENV:GITHUB_OUTPUT` and the ones that happen on mac/linux
need to be just `$GITHUB_OUTPUT`.
> fix: still working on GITHUB_OUTPUT

- Cargo.lock
- momento/Cargo.toml
- momento/src/commands/cloud_linter/dynamodb.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/metrics.rs
- momento/src/commands/cloud_linter/mod.rs
- momento/src/commands/cloud_linter/resource.rs
- momento/src/commands/cloud_linter/serverless_elasticache.rs
This pr updates the cloud linter command to be able to stream resources to a file, rather than keep everything in memory, before writing to a file
This main difference in this pr is that the entry point just calls `process_resource_<resource_name>`, and then the resource is in charge of getting all metadata/metrics, and then streaming the results to a file. Previously, the `process_resource` function would return the resources for further processing
> feat: stream resources to files

- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/s3.rs
- momento/src/commands/cloud_linter/serverless_elasticache.rs
Separate the metrics calls from the describe tables calls for elasticache and serverless elasticache. This lets us use a spinner for the describe calls, and then a standard progress bar for the metrics calls.
Remove an extra call to increment the s3 progress bar.
Add a progress bar to display that we are writing out the results file.
Misc linter fixes.
> chore: improve progress bars in cloud-linter

- momento-cli-opts/src/lib.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/configure/configure_cli.rs
- momento/src/main.rs
Make s3 and API gateway cloud linting optional.
> chore: make s3 and API gateway cloud linting optional

- momento-cli-opts/src/lib.rs
- momento/src/commands/cloud_linter/api_gateway.rs
- momento/src/commands/cloud_linter/dynamodb.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/metrics.rs
- momento/src/commands/cloud_linter/s3.rs
- momento/src/commands/cloud_linter/serverless_elasticache.rs
- momento/src/commands/cloud_linter/utils.rs
- momento/src/main.rs
Add optional arguments to the cloud-linter command that take a start and end date in YYYY-MM-DD form. If the start-date isn't provided, it defaults to end-date - 30. If end-date isn't provided, it defaults to today.
Make the process resources function argument orders consistent.
Delete some commented out code.
> feat: Make the cloud linter start and end dates configurable

- momento-cli-opts/src/lib.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/resource.rs
Add new cloud linter flags: elasti-cache-redis, elasti-cache-memcached, and elasti-cache-serverless, in addition to the existing elasti-cache flag. These limit the cloud linter to only process elasticache clusters with the redis or memcached engines, or only serverless clusters.
Add a stub section for valkey elasticache clusters, to be filled out in the future.
Make the unknown engine option return an empty vec instead of an error, because the previously unknown valkey engine was breaking processing when encountered.
> feat: add cloud linter options to filter by elasticache engine

- Makefile
- momento-cli-opts/src/lib.rs
- momento/src/commands/cloud_linter/elasticache.rs
- momento/src/commands/cloud_linter/linter_cli.rs
- momento/src/commands/cloud_linter/resource.rs
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1122
Made some demo caches in aws elasticache console. 
The homebrew published broke (did not process elasticache resources). 
The locally-built version of momento-cli of this branch appears to be working and scraping the valkey data though!
Essentially copied the elasticache redis components to do so. Let me know if there's anything else that should be tweaked though!
> Add ElastiCacheValkey resource

- momento/src/commands/cloud_linter/elasticache.rs
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1234
Verified that dynamodb metrics include read and write throttles ([reference](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html)). There's no throttling metric for elasticache, but found [ErrorCount](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/CacheMetrics.Redis.html#:~:text=Microseconds-,ErrorCount,-The%20total%20number), so taking the sum of that to include in the cloud linter data collection too.
> chore: add error_count_sum metric for elasticache resources in cloud linter

- momento/src/commands/topic/mod.rs
When displaying `Text` messages, we should use `Display` rather than `Debug`
This should ensure text with characters like `\n` are properly rendered
> chore: for topics subscribe messages, use Display instead of Debug
